---
title: "Project Plan"
author: "Scott Connors"
date: "27/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Title

...Something relating to predator prey size relationships...

## Abstract

...Very general explanation of the report...

## Contents

...

## Introduction

...Compact explanation of what kind of analysis I will be doing, and why fisheries science, and more specifically analysis of predator prey size relationships, are important in the context of the wider world (Modeling of food chains, predicting outcomes of predation events, understanding more about a relatively mysterious part of our planet)...

## Main bulk of report

## Ideas (Not necessarily in order):

Good practice to perform my own analysis and check to see if literature backs it up.

Some nice plots can be made looking at simply prey size and predator size with added regression lines (Scharf) for max,min,mean. (Different colours for the plot points of each species of prey fish)

predator/prey mass ratio(show through histograms how this is better analysed after a log transformation?),

## Work on actually writing out the bit above for 09/03/2021 ## (Mostly Done)

Fit distributions to log(pred/prey) mass ratio data (Normal distribution using MLE),

Check to see if some of the independence assumptions we make about the data are valid based off of data available to me (fish species select prey based off similar PPMR's throughout their lifetime, the same species living in different environments function the same (different latitudes), the same species function the same throughout the year)

Check to see if other distributions fit different species (or types of fish) better,

If I can find a dataset including gape size of predator fish, an interesting analysis would be to see if there is a noticeable relationship between gape size and PPMR. (seems relatively well reported in literature "Predator size - prey size relationships of marine fish predators: interspecific variation and effects of ontogeny and body size on trophic-niche breadth")


## Conclusion

...Short summary of the project...

## References

...



Timed plan (5 weeks left)

week 1; Create plots of prey size and predator size with scharf regression lines (useful to be able to see/predict max/min/average sizes of prey eaten by certain sizes of predators). Introduce PPMR.

week 2; Introduce fitting distributions to the logppmr data via MLE's and the formula's used to do so, also create graphical fits.

week 3; Continue working on fitting distribution to the data, more focus around checking to see if the independence assumptions are valid/ are other fits better/ identify what similarities there are between data fitting similar distributions. 

week 4; Abstract & introduction.

Final week; Finishing touches(conclusions, contents, check references, proof reading).

(extra time spent looking at gape size correlation)

(throughout identify key points to put on poster PPMR/Gaussian fit/MLE's)

